
package oracle.retail.integration.custom.gpfservices.cedisservice.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import oracle.retail.integration.custom.bo.cedisservice.v1.CeDisInvoiceRequest;
import oracle.retail.integration.custom.bo.cedisservice.v1.CeDisOrderRequest;
import oracle.retail.integration.custom.bo.cedisservice.v1.CeDisOrderRucRequest;
import oracle.retail.integration.custom.bo.cedisservice.v1.CeDisRTVRequest;
import oracle.retail.integration.custom.bo.cedisservice.v1.CeDisResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CeDisOrderService", targetNamespace = "http://oracle.com/retail/integration/custom/GPFServices/CeDisService/v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    oracle.retail.integration.custom.bo.cedisservice.v1.ObjectFactory.class,
    oracle.retail.integration.services.exception.v1.ObjectFactory.class
})
public interface CeDisOrderService {


    /**
     * 
     * @param payload
     * @return
     *     returns com.oracle.retail.integration.custom.bo.cedisservice.v1.CeDisResponse
     * @throws FaultExceptionMessage
     */
    @WebMethod(action = "getCeDisOrder")
    @WebResult(name = "CeDisResponse", targetNamespace = "http://oracle.com/retail/integration/custom/bo/CeDisService/v1", partName = "payload")
    public CeDisResponse getCeDisOrder(
        @WebParam(name = "CeDisOrderRequest", targetNamespace = "http://oracle.com/retail/integration/custom/bo/CeDisService/v1", partName = "payload")
        CeDisOrderRequest payload)
        throws FaultExceptionMessage
    ;

    /**
     * 
     * @param payload
     * @return
     *     returns com.oracle.retail.integration.custom.bo.cedisservice.v1.CeDisResponse
     * @throws FaultExceptionMessage
     */
    @WebMethod(action = "getCeDisInvoice")
    @WebResult(name = "CeDisResponse", targetNamespace = "http://oracle.com/retail/integration/custom/bo/CeDisService/v1", partName = "payload")
    public CeDisResponse getCeDisInvoice(
        @WebParam(name = "CeDisInvoiceRequest", targetNamespace = "http://oracle.com/retail/integration/custom/bo/CeDisService/v1", partName = "payload")
        CeDisInvoiceRequest payload)
        throws FaultExceptionMessage
    ;

    /**
     * 
     * @param payload
     * @return
     *     returns com.oracle.retail.integration.custom.bo.cedisservice.v1.CeDisResponse
     * @throws FaultExceptionMessage
     */
    @WebMethod(action = "getCeDisRTV")
    @WebResult(name = "CeDisResponse", targetNamespace = "http://oracle.com/retail/integration/custom/bo/CeDisService/v1", partName = "payload")
    public CeDisResponse getCeDisRTV(
        @WebParam(name = "CeDisRTVRequest", targetNamespace = "http://oracle.com/retail/integration/custom/bo/CeDisService/v1", partName = "payload")
        CeDisRTVRequest payload)
        throws FaultExceptionMessage
    ;

    /**
     * 
     * @param payload
     * @return
     *     returns com.oracle.retail.integration.custom.bo.cedisservice.v1.CeDisResponse
     * @throws FaultExceptionMessage
     */
    @WebMethod(action = "getCeDisOrderRuc")
    @WebResult(name = "CeDisResponse", targetNamespace = "http://oracle.com/retail/integration/custom/bo/CeDisService/v1", partName = "payload")
    public CeDisResponse getCeDisOrderRuc(
        @WebParam(name = "CeDisOrderRucRequest", targetNamespace = "http://oracle.com/retail/integration/custom/bo/CeDisService/v1", partName = "payload")
        CeDisOrderRucRequest payload)
        throws FaultExceptionMessage
    ;

}
