
package oracle.retail.integration.custom.gpfservices.cedisservice.v1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
//@WebServiceClient(name = "CeDisWS", targetNamespace = "http://oracle.com/retail/integration/custom/GPFServices/CeDisService/v1", wsdlLocation = "http://10.10.206.27:8001/soa-infra/services/test/CeDisService/CeDisWS?WSDL")
@WebServiceClient(name = "CeDisWS", targetNamespace = "http://oracle.com/retail/integration/custom/GPFServices/CeDisService/v1", wsdlLocation = "http://soa_dominio_mercaderia.gfybeca.int:8001/soa-infra/services/rms/CeDisService/CeDisWS?WSDL")
public class CeDisWS
    extends Service
{

    private final static URL CEDISWS_WSDL_LOCATION;
    private final static WebServiceException CEDISWS_EXCEPTION;
    private final static QName CEDISWS_QNAME = new QName("http://oracle.com/retail/integration/custom/GPFServices/CeDisService/v1", "CeDisWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
         //      url = new URL("http://10.10.206.27:8001/soa-infra/services/test/CeDisService/CeDisWS?WSDL");
          url = new URL("http://soa_dominio_mercaderia.gfybeca.int:8001/soa-infra/services/rms/CeDisService/CeDisWS?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CEDISWS_WSDL_LOCATION = url;
        CEDISWS_EXCEPTION = e;
    }

    public CeDisWS() {
        super(__getWsdlLocation(), CEDISWS_QNAME);
    }

    public CeDisWS(WebServiceFeature... features) {
        super(__getWsdlLocation(), CEDISWS_QNAME, features);
    }

    public CeDisWS(URL wsdlLocation) {
        super(wsdlLocation, CEDISWS_QNAME);
    }

    public CeDisWS(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CEDISWS_QNAME, features);
    }

    public CeDisWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CeDisWS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CeDisOrderService
     */
    @WebEndpoint(name = "CeDisOrderService_pt")
    public CeDisOrderService getCeDisOrderServicePt() {
        return super.getPort(new QName("http://oracle.com/retail/integration/custom/GPFServices/CeDisService/v1", "CeDisOrderService_pt"), CeDisOrderService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CeDisOrderService
     */
    @WebEndpoint(name = "CeDisOrderService_pt")
    public CeDisOrderService getCeDisOrderServicePt(WebServiceFeature... features) {
        return super.getPort(new QName("http://oracle.com/retail/integration/custom/GPFServices/CeDisService/v1", "CeDisOrderService_pt"), CeDisOrderService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CEDISWS_EXCEPTION!= null) {
            throw CEDISWS_EXCEPTION;
        }
        return CEDISWS_WSDL_LOCATION;
    }

}
