
package oracle.retail.integration.custom.gpfservices.cedisservice.v1;

import javax.xml.ws.WebFault;
import oracle.retail.integration.services.exception.v1.FaultException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "FaultException", targetNamespace = "http://www.oracle.com/retail/integration/services/exception/v1")
public class FaultExceptionMessage
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private FaultException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public FaultExceptionMessage(String message, FaultException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public FaultExceptionMessage(String message, FaultException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.oracle.retail.integration.services.exception.v1.FaultException
     */
    public FaultException getFaultInfo() {
        return faultInfo;
    }

}
