package com.gizlocorp.gnvoice.wsclient.guia;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.7.redhat-1
 * 2014-08-05T18:23:04.477-05:00
 * Generated source version: 2.7.7.redhat-1
 * 
 */
@WebServiceClient(name = "Guia", 
                  wsdlLocation = "http://localhost:18080/Guia/Guia?wsdl",
                  targetNamespace = "urn:com.gizlocorp.gnvoice:gnvoice-sca:1.0") 
public class Guia extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:com.gizlocorp.gnvoice:gnvoice-sca:1.0", "Guia");
    public final static QName GuiaPort = new QName("urn:com.gizlocorp.gnvoice:gnvoice-sca:1.0", "GuiaPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:18080/Guia/Guia?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Guia.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:18080/Guia/Guia?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Guia(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Guia(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Guia() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Guia(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Guia(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Guia(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns GuiaPortType
     */
    @WebEndpoint(name = "GuiaPort")
    public GuiaPortType getGuiaPort() {
        return super.getPort(GuiaPort, GuiaPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GuiaPortType
     */
    @WebEndpoint(name = "GuiaPort")
    public GuiaPortType getGuiaPort(WebServiceFeature... features) {
        return super.getPort(GuiaPort, GuiaPortType.class, features);
    }

}
