package com.gizlocorp.gnvoice.wsclient.guia;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.7.redhat-1
 * 2014-08-05T18:23:04.451-05:00
 * Generated source version: 2.7.7.redhat-1
 * 
 */
@WebService(targetNamespace = "urn:com.gizlocorp.gnvoice:gnvoice-sca:1.0", name = "GuiaPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface GuiaPortType {

    @WebResult(name = "guiaRecibirResponse", targetNamespace = "urn:com.gizlocorp.gnvoice:gnvoice-sca:1.0", partName = "guiaRecibirResponse")
    @WebMethod(action = "recibir")
    public GuiaRecibirResponse recibir(
        @WebParam(partName = "guiaRecibirRequest", name = "guiaRecibirRequest", targetNamespace = "urn:com.gizlocorp.gnvoice:gnvoice-sca:1.0")
        GuiaRecibirRequest guiaRecibirRequest
    );

    @WebResult(name = "guiaProcesarResponse", targetNamespace = "urn:com.gizlocorp.gnvoice:gnvoice-sca:1.0", partName = "guiaProcesarResponse")
    @WebMethod(action = "procesar")
    public GuiaProcesarResponse procesar(
        @WebParam(partName = "guiaProcesarRequest", name = "guiaProcesarRequest", targetNamespace = "urn:com.gizlocorp.gnvoice:gnvoice-sca:1.0")
        GuiaProcesarRequest guiaProcesarRequest
    );

    @WebResult(name = "guiaConsultarResponse", targetNamespace = "urn:com.gizlocorp.gnvoice:gnvoice-sca:1.0", partName = "guiaConsultarResponse")
    @WebMethod(action = "consultar")
    public GuiaConsultarResponse consultar(
        @WebParam(partName = "guiaConsultarRequest", name = "guiaConsultarRequest", targetNamespace = "urn:com.gizlocorp.gnvoice:gnvoice-sca:1.0")
        GuiaConsultarRequest guiaConsultarRequest
    );
}
