package com.gizlocorp.gnvoice.wsclient.notacredito;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.7.redhat-1
 * 2014-08-05T18:27:03.569-05:00
 * Generated source version: 2.7.7.redhat-1
 * 
 */
@WebService(targetNamespace = "urn:com.gizlocorp.gnvoice:gnvoice-sca:1.0", name = "NotaCreditoPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface NotaCreditoPortType {

    @WebResult(name = "notaCreditoRecibirResponse", targetNamespace = "urn:com.gizlocorp.gnvoice:gnvoice-sca:1.0", partName = "notaCreditoRecibirResponse")
    @WebMethod(action = "recibir")
    public NotaCreditoRecibirResponse recibir(
        @WebParam(partName = "notaCreditoRecibirRequest", name = "notaCreditoRecibirRequest", targetNamespace = "urn:com.gizlocorp.gnvoice:gnvoice-sca:1.0")
        NotaCreditoRecibirRequest notaCreditoRecibirRequest
    );

    @WebResult(name = "notaCreditoProcesarResponse", targetNamespace = "urn:com.gizlocorp.gnvoice:gnvoice-sca:1.0", partName = "notaCreditoProcesarResponse")
    @WebMethod(action = "procesar")
    public NotaCreditoProcesarResponse procesar(
        @WebParam(partName = "notaCreditoProcesarRequest", name = "notaCreditoProcesarRequest", targetNamespace = "urn:com.gizlocorp.gnvoice:gnvoice-sca:1.0")
        NotaCreditoProcesarRequest notaCreditoProcesarRequest
    );

    @WebResult(name = "notaCreditoConsultarResponse", targetNamespace = "urn:com.gizlocorp.gnvoice:gnvoice-sca:1.0", partName = "notaCreditoConsultarResponse")
    @WebMethod(action = "consultar")
    public NotaCreditoConsultarResponse consultar(
        @WebParam(partName = "notaCreditoConsultarRequest", name = "notaCreditoConsultarRequest", targetNamespace = "urn:com.gizlocorp.gnvoice:gnvoice-sca:1.0")
        NotaCreditoConsultarRequest notaCreditoConsultarRequest
    );
}
