package com.gizlocorp.gnvoice.wsclient.notacredito;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.7.redhat-1
 * 2014-08-05T18:27:03.596-05:00
 * Generated source version: 2.7.7.redhat-1
 * 
 */
@WebServiceClient(name = "NotaCredito", 
                  wsdlLocation = "http://localhost:8330/NotaCredito/NotaCredito?wsdl",
                  targetNamespace = "urn:com.gizlocorp.gnvoice:gnvoice-sca:1.0") 
public class NotaCredito_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:com.gizlocorp.gnvoice:gnvoice-sca:1.0", "NotaCredito");
    public final static QName NotaCreditoPort = new QName("urn:com.gizlocorp.gnvoice:gnvoice-sca:1.0", "NotaCreditoPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8330/NotaCredito/NotaCredito?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(NotaCredito_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8330/NotaCredito/NotaCredito?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public NotaCredito_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public NotaCredito_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NotaCredito_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public NotaCredito_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public NotaCredito_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public NotaCredito_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns NotaCreditoPortType
     */
    @WebEndpoint(name = "NotaCreditoPort")
    public NotaCreditoPortType getNotaCreditoPort() {
        return super.getPort(NotaCreditoPort, NotaCreditoPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NotaCreditoPortType
     */
    @WebEndpoint(name = "NotaCreditoPort")
    public NotaCreditoPortType getNotaCreditoPort(WebServiceFeature... features) {
        return super.getPort(NotaCreditoPort, NotaCreditoPortType.class, features);
    }

}
