package com.gizlocorp.gnvoice.wsclient.notadebito;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.7.redhat-1
 * 2014-08-05T18:28:23.248-05:00 Generated source version: 2.7.7.redhat-1
 * 
 */
@WebService(targetNamespace = "urn:com.gizlocorp.gnvoice:gnvoice-sca:1.0", name = "NotaDebitoPortType")
@XmlSeeAlso({ ObjectFactory.class })
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface NotaDebitoPortType {

	@WebResult(name = "notaDebitoRecibirResponse", targetNamespace = "urn:com.gizlocorp.gnvoice:gnvoice-sca:1.0", partName = "notaDebitoRecibirResponse")
	@WebMethod(action = "recibir")
	public NotaDebitoRecibirResponse recibir(
			@WebParam(partName = "notaDebitoRecibirRequest", name = "notaDebitoRecibirRequest", targetNamespace = "urn:com.gizlocorp.gnvoice:gnvoice-sca:1.0") NotaDebitoRecibirRequest notaDebitoRecibirRequest);

	@WebResult(name = "notaDebitoProcesarResponse", targetNamespace = "urn:com.gizlocorp.gnvoice:gnvoice-sca:1.0", partName = "notaDebitoProcesarResponse")
	@WebMethod(action = "procesar")
	public NotaDebitoProcesarResponse procesar(
			@WebParam(partName = "notaDebitoProcesarRequest", name = "notaDebitoProcesarRequest", targetNamespace = "urn:com.gizlocorp.gnvoice:gnvoice-sca:1.0") NotaDebitoProcesarRequest notaDebitoProcesarRequest);

	@WebResult(name = "notaDebitoConsultarResponse", targetNamespace = "urn:com.gizlocorp.gnvoice:gnvoice-sca:1.0", partName = "notaDebitoConsultarResponse")
	@WebMethod(action = "consultar")
	public NotaDebitoConsultarResponse consultar(
			@WebParam(partName = "notaDebitoConsultarRequest", name = "notaDebitoConsultarRequest", targetNamespace = "urn:com.gizlocorp.gnvoice:gnvoice-sca:1.0") NotaDebitoConsultarRequest notaDebitoConsultarRequest);
}
