package com.gizlocorp.gnvoice.firmaelectronica.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.6-redhat-3
 * 2014-04-01T15:21:55.213-05:00
 * Generated source version: 2.6.6-redhat-3
 * 
 */
@WebService(targetNamespace = "http://service.firmaelectronica.gizlocorp.com/", name = "FirmaElectronicaWs")
@XmlSeeAlso({ObjectFactory.class})
public interface FirmaElectronicaWs {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "firmarDocumento", targetNamespace = "http://service.firmaelectronica.gizlocorp.com/", className = "com.gizlocorp.gnvoice.firmaelectronica.ws.FirmarDocumento")
    @WebMethod
    @ResponseWrapper(localName = "firmarDocumentoResponse", targetNamespace = "http://service.firmaelectronica.gizlocorp.com/", className = "com.gizlocorp.gnvoice.firmaelectronica.ws.FirmarDocumentoResponse")
    public com.gizlocorp.gnvoice.firmaelectronica.ws.FirmaElectronicaResponse firmarDocumento(
        @WebParam(name = "arg0", targetNamespace = "")
        com.gizlocorp.gnvoice.firmaelectronica.ws.FirmaElectronicaRequest arg0
    );
}
