package com.gizlocorp.gnvoice.firmaelectronica.ws;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.6.6-redhat-3
 * 2014-04-01T15:21:55.313-05:00 Generated source version: 2.6.6-redhat-3
 * 
 */
@WebServiceClient(name = "FirmaElectronicaWsService", wsdlLocation = "http://localhost:8330/gnvoiceFirma/FirmaElectronicaWs?WSDL", targetNamespace = "http://service.firmaelectronica.gizlocorp.com/")
public class FirmaElectronicaWsService extends Service {

	public final static URL WSDL_LOCATION;

	public final static QName SERVICE = new QName(
			"http://service.firmaelectronica.gizlocorp.com/",
			"FirmaElectronicaWsService");
	public final static QName FirmaElectronicaWsPort = new QName(
			"http://service.firmaelectronica.gizlocorp.com/",
			"FirmaElectronicaWsPort");
	static {
		URL url = null;
		try {
			url = new URL(
					"http://localhost:8330/gnvoiceFirma/FirmaElectronicaWs?WSDL");
		} catch (MalformedURLException e) {
			java.util.logging.Logger
					.getLogger(FirmaElectronicaWsService.class.getName())
					.log(java.util.logging.Level.INFO,
							"Can not initialize the default wsdl from {0}",
							"http://localhost:8330/gnvoiceFirma/FirmaElectronicaWs?WSDL");
		}
		WSDL_LOCATION = url;
	}

	public FirmaElectronicaWsService(URL wsdlLocation) {
		super(wsdlLocation, SERVICE);
	}

	public FirmaElectronicaWsService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public FirmaElectronicaWsService() {
		super(WSDL_LOCATION, SERVICE);
	}

	/**
	 * 
	 * @return returns FirmaElectronicaWs
	 */
	@WebEndpoint(name = "FirmaElectronicaWsPort")
	public FirmaElectronicaWs getFirmaElectronicaWsPort() {
		return super.getPort(FirmaElectronicaWsPort, FirmaElectronicaWs.class);
	}

	/**
	 * 
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
	 *            on the proxy. Supported features not in the
	 *            <code>features</code> parameter will have their default
	 *            values.
	 * @return returns FirmaElectronicaWs
	 */
	@WebEndpoint(name = "FirmaElectronicaWsPort")
	public FirmaElectronicaWs getFirmaElectronicaWsPort(
			WebServiceFeature... features) {
		return super.getPort(FirmaElectronicaWsPort, FirmaElectronicaWs.class,
				features);
	}

}
