package com.gizlocorp.gnvoice.wsclient.factura;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-08-05T18:07:36.356-05:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "Factura", 
                  wsdlLocation = "http://localhost:8330/Factura/Factura?wsdl",//"http://localhost:8330/Factura/Factura?wsdl"
                  targetNamespace = "urn:com.gizlocorp.gnvoice:gnvoice-sca:1.0") 
public class Factura_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:com.gizlocorp.gnvoice:gnvoice-sca:1.0", "Factura");
    public final static QName FacturaPort = new QName("urn:com.gizlocorp.gnvoice:gnvoice-sca:1.0", "FacturaPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8330/Factura/Factura?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Factura_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8330/Factura/Factura?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Factura_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Factura_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Factura_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Factura_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Factura_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Factura_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns FacturaPortType
     */
    @WebEndpoint(name = "FacturaPort")
    public FacturaPortType getFacturaPort() {
        return super.getPort(FacturaPort, FacturaPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FacturaPortType
     */
    @WebEndpoint(name = "FacturaPort")
    public FacturaPortType getFacturaPort(WebServiceFeature... features) {
        return super.getPort(FacturaPort, FacturaPortType.class, features);
    }

}
