package com.gizlocorp.gnvoice.wsclient.factura;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-08-05T18:07:36.283-05:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "urn:com.gizlocorp.gnvoice:gnvoice-sca:1.0", name = "FacturaPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface FacturaPortType {

    @WebResult(name = "facturaRecibirResponse", targetNamespace = "urn:com.gizlocorp.gnvoice:gnvoice-sca:1.0", partName = "facturaRecibirResponse")
    @WebMethod(action = "recibir")
    public FacturaRecibirResponse recibir(
        @WebParam(partName = "facturaRecibirRequest", name = "facturaRecibirRequest", targetNamespace = "urn:com.gizlocorp.gnvoice:gnvoice-sca:1.0")
        FacturaRecibirRequest facturaRecibirRequest
    );

    @WebResult(name = "facturaProcesarResponse", targetNamespace = "urn:com.gizlocorp.gnvoice:gnvoice-sca:1.0", partName = "facturaProcesarResponse")
    @WebMethod(action = "procesar")
    public FacturaProcesarResponse procesar(
        @WebParam(partName = "facturaProcesarRequest", name = "facturaProcesarRequest", targetNamespace = "urn:com.gizlocorp.gnvoice:gnvoice-sca:1.0")
        FacturaProcesarRequest facturaProcesarRequest
    );

    @WebResult(name = "facturaConsultarResponse", targetNamespace = "urn:com.gizlocorp.gnvoice:gnvoice-sca:1.0", partName = "facturaConsultarResponse")
    @WebMethod(action = "consultar")
    public FacturaConsultarResponse consultar(
        @WebParam(partName = "facturaConsultarRequest", name = "facturaConsultarRequest", targetNamespace = "urn:com.gizlocorp.gnvoice:gnvoice-sca:1.0")
        FacturaConsultarRequest facturaConsultarRequest
    );
}
